project:
  type: website
  output-dir: docs

website:
  title: "Elena Pro"
  favicon: favicon-32x32.png
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd  
      - teaching.qmd
      - blog.qmd
     
    tools:
      - icon: twitter
        href: https://twitter.com/elenapro0
      - icon: github
        href: https://github.com/elena-pr
      - icon: linkedin
        href: https://www.linkedin.com/in/elena-pro-69a9a41a1/
      - icon: envelope
        href: mailto:e.pro@lse.ac.uk
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

