project:
  type: website
  output-dir: docs

website:
  title: "Elena Pro"
  favicon: favicon-32x32.png
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - blog.qmd 
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

